name: wakatime
description: An unofficial mobile app for wakatime
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^3.0.6

flutter:
  uses-material-design: true

import_sorter:
  emojis: true
